-- Firebase Auth's `picture` claim is an external URL, not a Firebase Storage
-- path. Only paths generated by the controlled profile-image upload flow may
-- be kept in avatar_storage_path.
UPDATE users
SET avatar_storage_path = NULL
WHERE avatar_storage_path ~* '^https?://';
